### ISSUE TITLE
When trying to run a Survey using a removed channel an exception is thrown...

### ISSUE THREAD

**Issue by mmuller** [instedd/ask#1160]
...We should display the cause of the problem in order to give more information to the user.

Prerequisites:
There is a Channel `C`.

Reproduce steps:
Remove `C` from the provider.
Create a Survey.
Select `C` as channel.
Complete the wizard.
Launch the Survey.

Obtained:
The following error is displayed:
`Something went wrong
Unhandled promise rejection
Error ID:
c1af57c653e844c1baa460388d41f1b7
Call stack
Error: Unhandled promise rejection
    at https://surveda-stg.instedd.org/js/app.js:91:348472
    at t (https://surveda-stg.instedd.org/js/app.js:119:110547)`

Expected:
We should display something like: 
`The survey cannot be started because the channel was not found`.

**Comment by manumoreira** [comment]
related to #524
